default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: focushub_development
  # cable:
    # <<: *default
    # database: focushub_development_cable
    # migrations_paths: db/cable_migrate

test:
  <<: *default
  database: focushub_test


production:
  primary: &primary_production
    <<: *default
    # database: focushub_production
    # username: focushub
    # password: <%= ENV["FOCUSHUB_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: focushub_production_cache
    migrations_paths: db/cache_migrate
    url: <%= if Rails.env.production? && ENV["DATABASE_URL"]&.match(%r{/[^/?#]+$}) then ENV["DATABASE_URL"].sub(%r{(/[^/?#]+)$}, "\\1_cache") end %>
  queue:
    <<: *primary_production
    database: focushub_production_queue
    migrations_paths: db/queue_migrate
    url: <%= if Rails.env.production? && ENV["DATABASE_URL"]&.match(%r{/[^/?#]+$}) then ENV["DATABASE_URL"].sub(%r{(/[^/?#]+)$}, "\\1_queue") end %>
  cable:
    <<: *primary_production
    database: focushub_production_cable
    migrations_paths: db/cable_migrate
    url: <%= if Rails.env.production? && ENV["DATABASE_URL"]&.match(%r{/[^/?#]+$}) then ENV["DATABASE_URL"].sub(%r{(/[^/?#]+)$}, "\\1_cable") end %>
